$ANSIBLE_VAULT;1.1;AES256
65623033663361333436656138666166306462616239346264663836303334393337356465386539
3765383933643863333932646436343033336134663438630a616561343966376236303731326661
38316661643663336631343231653032313631646131613331383434303236613539396166393834
6232383264663462660a333361356335323338623431376130393563653633663765326266613637
39656433386236326161313035363031616561343735333631626434353639376138666432353663
64353866326366666165623536613238663839623865303536373534613365386438363730366166
36613130306662666664646330643636306561663131646662303733613339326330346238313335
64386661306236393130366161313764316634316164616634323139646434366133646365313665
6263
