---
- name: start an instance with a public IP address
  amazon.aws.ec2_instance:
    name: "{{ item.name }}"
    key_name: "new"
    instance_type: t2.micro
    security_groups:
      - default
    region: ap-south-1
    aws_access_key: "{{ ec2_access_key }}"
    aws_secret_key: "{{ ec2_secret_key }}"
    network:
      assign_public_ip: true
    # Use item.image here, not item.name
    image_id: "{{ item.image }}"
    tags:
      Environment: "{{ item.name }}"
  loop:
    - { image: "ami-0ff5003538b60d5ec", name: "manager-name-1" }
    - { image: "ami-019715e0d74f695be", name: "manager-name-2" }
    - { image: "ami-019715e0d74f695be", name: "manager-name-3" }
